In [1]:
import numpy as np
import pandas as pd


1. Define Variable & Activation Function

In [2]:
def relu(x):
    return np.maximum(0, x)

def relu_deriv(x):
    return (x > 0).astype(float)

def mse_loss(y_pred, y_true):
    return 0.5 * (y_pred - y_true)**2

In [3]:
lr = 0.01
b = 1

In [4]:
x = np.array([
    [-4, 3],
    [1, 0]
])

y = np.array([
    [-1],
    [5]
])

W1 = np.array([
    [2.0, -1.0, 1.0], 
    [1.0,  -2.0, -1.0]
])
b1 = np.full((1, 3), b)

W2 = np.array([
    [1.0,  3.0], 
    [-2.0, 1.0], 
    [2.0, -2.0]
])
b2 = np.full((1, 2), b)


W3 = np.array([
    [-2.0],
    [3.0]
])
b3 = np.full((1, 1), b)

2. Hidden Layer 1 & 2

In [5]:
Z1 = np.dot(x, W1) + b1
A1 = relu(Z1)

Z2 = np.dot(A1, W2) + b2
A2 = relu(Z2)

Z3 = np.dot(A2, W3) + b3
output = Z3 

n = x.shape[0]
loss_mse = np.mean(np.square(y - output))

In [6]:
print("=" * 20, "Hasil", "=" * 20)
print(f"Z1 = \n {Z1}")
print(f"Z2 = \n {Z2}")
print(f"Z3 = \n {Z3}")

print(f"A1 = \n {A1}")
print(f"A2 = \n {A2}")

print("=" * 47)
print(f"Prediksi:\n{output}")
print(f"MSE Loss:\n{loss_mse}")


==================== Hasil ====================
Z1 = 
 [[-4. -1. -6.]
 [ 3.  0.  2.]]
Z2 = 
 [[1. 1.]
 [8. 6.]]
Z3 = 
 [[2.]
 [3.]]
A1 = 
 [[0. 0. 0.]
 [3. 0. 2.]]
A2 = 
 [[1. 1.]
 [8. 6.]]
Prediksi:
[[2.]
 [3.]]
MSE Loss:
6.5


3. Backward Pass

In [7]:
delta_loss_out = (2 / n) * (output - y)

deriv_W3 = np.dot(A2.T, delta_loss_out)
deriv_B3 = np.sum(delta_loss_out, axis = 0, keepdims = True)

deriv_A2 = np.dot(delta_loss_out, W3.T)
deriv_Z2 = deriv_A2 * relu_deriv(Z2)
deriv_W2 = np.dot(A1.T, deriv_Z2)
deriv_B2 = np.sum(deriv_Z2, axis=0, keepdims=True)


deriv_A1 = np.dot(deriv_A2, W2.T)
deriv_Z1 = deriv_A1 * relu_deriv(Z1)
deriv_W1 = np.dot(x.T, deriv_Z1)
deriv_B1 = np.sum(deriv_Z1, axis=0, keepdims=True)

In [8]:
print("=" * 20, "Backward Pass", "=" * 20)

print("derivative W3:\n", deriv_W3)
print("derivative B3:\n", deriv_B3)

print("derivative A2:\n", deriv_A2)
print("derivative Z2:\n", deriv_Z2)
print("derivative W2:\n", deriv_W2)
print("derivative B2:\n", deriv_B2)

print("derivative A1:\n", deriv_A1)
print("derivative Z1:\n", deriv_Z1)
print("derivative W1:\n", deriv_W1)
print("derivative B1:\n", deriv_B1)

==================== Backward Pass ====================
derivative W3:
 [[-13.]
 [ -9.]]
derivative B3:
 [[1.]]
derivative A2:
 [[-6.  9.]
 [ 4. -6.]]
derivative Z2:
 [[-6.  9.]
 [ 4. -6.]]
derivative W2:
 [[ 12. -18.]
 [  0.   0.]
 [  8. -12.]]
derivative B2:
 [[-2.  3.]]
derivative A1:
 [[ 21.  21. -30.]
 [-14. -14.  20.]]
derivative Z1:
 [[  0.   0.  -0.]
 [-14.  -0.  20.]]
derivative W1:
 [[-14.   0.  20.]
 [  0.   0.   0.]]
derivative B1:
 [[-14.   0.  20.]]


4. Update Weights

In [9]:
W1_new = W1 - lr * deriv_W1
W2_new = W2 - lr * deriv_W2
W3_new = W3 - lr * deriv_W3

B1_new = b1 - lr * deriv_B1
B2_new = b2 - lr * deriv_B2
B3_new = b3 - lr * deriv_B3


In [10]:
print("=" * 20 ,"\nWeights Baru (setelah 1 step):", "=" * 20)
print("W1 New:\n", W1_new)
print("W2 New:\n", W2_new)
print("W3 New:\n", W3_new, '\n\n')

print("B1 New:\n", B1_new)
print("B2 New:\n", B2_new)
print("B3 New:\n", B3_new)

Weights Baru (setelah 1 step): ====================
W1 New:
 [[ 2.14 -1.    0.8 ]
 [ 1.   -2.   -1.  ]]
W2 New:
 [[ 0.88  3.18]
 [-2.    1.  ]
 [ 1.92 -1.88]]
W3 New:
 [[-1.87]
 [ 3.09]] 


B1 New:
 [[1.14 1.   0.8 ]]
B2 New:
 [[1.02 0.97]]
B3 New:
 [[0.99]]
